openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore Draft
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
  - url: http://test.petstore.swagger.io/v1
    description: the PetStore test server
security:
  - api_id: ['X-API-Key']
paths:
  /pets:
    get:
      summary: 'GET'
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: 'Maximim is 100'
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: 'OK'
          headers:
            x-next:
              description: 'Next page'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'POST'
      operationId: createPets
      tags:
        - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '201':
          description: 'POST Error'
        default:
          description: 'toUpload error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}:
    get:
      summary: 'GET pet ID'
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: 'Pet ID'
          schema:
            type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: 'Request is refused'
        '404':
          description: 'URI not found'
        default:
          description: 'Error description'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    api_id:
      description: API Key for swagger. Ask an admin if you do not have any.
      type: apiKey
      name: api-key
      in: header

        