openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore Draft
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
    description: основной сервер Petstore
  - url: http://test.petstore.swagger.io/v1
    description: Тестовый сервер PetStore 
security:
  - api_id: ['X-API-Key']
paths:
  /pets:
    get:
      summary: 'Получить список питомцев'
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: 'Максимальная длина 100 записей'
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: 'Успешный запрос'
          headers:
            x-next:
              description: 'Следующая страница'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: 'Ошибка'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'Создать запись питомца'
      operationId: createPets
      tags:
        - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '201':
          description: 'Запись создана'
        default:
          description: 'Ошибка записи'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}:
    get:
      summary: 'Получить ID питомца'
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: 'ID питомца'
          schema:
            type: string
      responses:
        '200':
          description: 'ID получено успешно'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: 'Запрос отклонен'
        '404':
          description: 'Не найден URI'
        default:
          description: 'Ошибка запроса'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    api_id:
      description: Введите API Key для swagger. Если у вас нет ключа, обратитесь к администратору. 
      type: apiKey
      name: api-key
      in: header

        